defaults:
  - experiment_T5_V3_HybridGlobalLocalCrossAttn

audio_path: "audio/piano_test.mp3"

model:
  checkpoint_path: checkpoints/Baseline_120k_NoExtentions.ckpt #checkpoints/T5_V4_steps_200000-OG.ckpt
  cross_attention_hierarchy_pooling: true
  pooling_sizes: [4, 4, 2, 2, 1, 1]

  # pooling_sizes: [4, 4, 4, 4, 4, 4]

data:
  # true => pedal-extended note offsets from offset_sec
  # false => raw physical key-release offsets from offset_sec_truth
  use_note_extensions: false

training:
  training_steps: 120000
  # resume_ckpt_path: /home/rachel/.group-5/Piano-AMT-HRM/Backend/efficient-seq2seq-piano-trans/runs/Transformer-T5/260414-005926_Efficient_Transformer_V4_HierarchyPool_noteExtensions=False/cpt/full/last.ckpt
  notes: "Efficient_Transformer_V4_HierarchyPool_noteExtensions=${data.use_note_extensions}"
  
