defaults:
  - experiment_T5_V3_HybridGlobalLocalCrossAttn

audio_path: "audio/piano_test.mp3"

model:
  checkpoint_path: checkpoints/T5_V4_steps_200000-OG.ckpt

  cross_attention_hierarchy_pooling: true
  pooling_sizes: [4, 4, 2, 2, 1, 1]

  # pooling_sizes: [4, 4, 4, 4, 4, 4]

data:
  training_steps: 45000
  # true => pedal-extended note offsets from offset_sec
  # false => raw physical key-release offsets from offset_sec_truth
  use_note_extensions: true

training:
  notes: "Efficient_Transformer_V4_HierarchyPool_noteExtensions=${data.use_note_extensions}"
  
